### PR TITLE
Fix.ngpaste.jquery

### LINKED ISSUE #441: Directive which use ng-paste don't work if JQuery is loaded before Angular
If the project where lucca-ui is used requires JQuery, all events are transformed by JQuery, which causes errors most notably in the directives `luid-iban` and `luid-translations-list`, which use the `ng-paste` directive.

### PR DESCRIPTION
**Pull request by bastienguillon**
Fixed issues in `luid-iban` and `luid-translations-list` which happened on projects which uses JQuery and load it before Angular. JQuery overlays all the JS events, which makes `ng-paste` directive unusable. 

fixes #441 

Also, fixed some issues with `luid-translations-list`:
- added unique added to each input displayed in the directive, to be able to display multiple times on the same page
- fixed an issue where the directive didn't work when the ng-model was defined but empty

### CODE REVIEW

File: ts/translations-list/translations-list.directive.ts [hunk 1]
```diff
@@ -123,16 +130,19 @@ module lui.translate {
 			let mode = attrs.mode;
 			if (!mode) { mode = "lucca"; }
 
+			// Unique identifier
+			scope.uniqueId = (Math.floor(Math.random() * 9000) + 1).toString();
```
Comment (PaulAndreLOUIS) [inline ts/translations-list/translations-list.directive.ts]: it's over nine thousand !

**Comment by bastienguillon** [comment]
C'est bon pour toi @lucienbertin ?
